"""improved

Revision ID: 1ef1a20993ab
Revises: 
Create Date: 2025-01-22 16:48:04.816267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ef1a20993ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mod_id', sa.String(length=50), nullable=False),
    sa.Column('mod_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mods_mod_id'), ['mod_id'], unique=True)

    op.create_table('telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mod_id', sa.Integer(), nullable=False),
    sa.Column('game_version', sa.String(length=10), nullable=False),
    sa.Column('mod_version', sa.String(length=10), nullable=False),
    sa.Column('loader', sa.String(length=25), nullable=False),
    sa.Column('usage_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mod_id'], ['mods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telemetry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telemetry_game_version'), ['game_version'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetry_mod_version'), ['mod_version'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telemetry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telemetry_mod_version'))
        batch_op.drop_index(batch_op.f('ix_telemetry_game_version'))

    op.drop_table('telemetry')
    with op.batch_alter_table('mods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mods_mod_id'))

    op.drop_table('mods')
    # ### end Alembic commands ###
