"""Add loader column to Telemetry model

Revision ID: 553ca07ab1b8
Revises: 
Create Date: 2025-01-05 11:29:10.309367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '553ca07ab1b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telemetry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loader', sa.String(length=25), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telemetry', schema=None) as batch_op:
        batch_op.drop_column('loader')

    # ### end Alembic commands ###
