name: Build and deploy Python app to Azure Web App - anvian-telemetry
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Prepare deployment scripts
        run: |
          echo '#!/bin/bash
          pwd
          ls
          python -m flask --version
          flask db upgrade
          gunicorn --bind 0.0.0.0:8000 app:app' > startup.sh
          chmod +x startup.sh
      - name: Create debug file
        run: |
          echo 'Python version:' > debug.txt
          python --version >> debug.txt
          echo 'Installed packages:' >> debug.txt
          pip freeze >> debug.txt
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/
            debug.txt
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      - name: Unzip artifact for deployment
        run: unzip -o release.zip
      - name: Show debug information
        run: cat debug.txt
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0C5C24F849BA42B299BF0A024071E9B9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0AB99FA450224880A9672B96B72FFA08 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6263B82411EE487F94D286C281039C08 }}
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'anvian-telemetry'
          slot-name: 'Production'
          startup-command: 'bash startup.sh'